name: budget_app
description: "Une application de gestion de budget complète"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  
  # Authentication
  google_sign_in: ^6.3.0
  
  # Storage
  shared_preferences: ^2.5.3
  
  # UI & Charts
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true