// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo6YI-dW7tp4PfoBFNwXDuMy1zya1aLJ0',
    appId: '1:570468917791:web:dc27ad5b146b4629e96b2a',
    messagingSenderId: '570468917791',
    projectId: 'budget-app-pro',
    authDomain: 'budget-app-pro.firebaseapp.com',
    storageBucket: 'budget-app-pro.firebasestorage.app',
    measurementId: 'G-BF88P0J6TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqW-ffCerW0F35NXfEVrlpdoEgD-UbHJ8',
    appId: '1:570468917791:android:c624c82628b7348ce96b2a',
    messagingSenderId: '570468917791',
    projectId: 'budget-app-pro',
    storageBucket: 'budget-app-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAHsIiphbdtXLFPlsB6YpJB2D-SWNHdw',
    appId: '1:570468917791:ios:0dbd520c9ea9c4f0e96b2a',
    messagingSenderId: '570468917791',
    projectId: 'budget-app-pro',
    storageBucket: 'budget-app-pro.firebasestorage.app',
    iosClientId: '570468917791-a6bjtsqjvq6690pl92mefvbrmo1lm34j.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6YI-dW7tp4PfoBFNwXDuMy1zya1aLJ0',
    appId: '1:570468917791:ios:REMPLACER_PAR_IOS_APP_ID',
    messagingSenderId: '570468917791',
    projectId: 'budget-app-pro',
    storageBucket: 'budget-app-pro.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo6YI-dW7tp4PfoBFNwXDuMy1zya1aLJ0',
    appId: '1:570468917791:web:dc27ad5b146b4629e96b2a',
    messagingSenderId: '570468917791',
    projectId: 'budget-app-pro',
    authDomain: 'budget-app-pro.firebaseapp.com',
    storageBucket: 'budget-app-pro.firebasestorage.app',
  );
}