// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIU3gJwizb5mc3ida_nmVLk2_-VhJ17kc',
    appId: '1:320883807207:web:d90aa3515557e7b9d9e342',
    messagingSenderId: '320883807207',
    projectId: 'budget-app-26741',
    authDomain: 'budget-app-26741.firebaseapp.com',
    storageBucket: 'budget-app-26741.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIU3gJwizb5mc3ida_nmVLk2_-VhJ17kc',
    appId: '1:320883807207:android:d90aa3515557e7b9d9e342',
    messagingSenderId: '320883807207',
    projectId: 'budget-app-26741',
    storageBucket: 'budget-app-26741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIU3gJwizb5mc3ida_nmVLk2_-VhJ17kc',
    appId: '1:320883807207:ios:d90aa3515557e7b9d9e342',
    messagingSenderId: '320883807207',
    projectId: 'budget-app-26741',
    storageBucket: 'budget-app-26741.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIU3gJwizb5mc3ida_nmVLk2_-VhJ17kc',
    appId: '1:320883807207:ios:d90aa3515557e7b9d9e342',
    messagingSenderId: '320883807207',
    projectId: 'budget-app-26741',
    storageBucket: 'budget-app-26741.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIU3gJwizb5mc3ida_nmVLk2_-VhJ17kc',
    appId: '1:320883807207:web:d90aa3515557e7b9d9e342',
    messagingSenderId: '320883807207',
    projectId: 'budget-app-26741',
    authDomain: 'budget-app-26741.firebaseapp.com',
    storageBucket: 'budget-app-26741.firebasestorage.app',
  );
}